# Generated by Django 3.2.14 on 2022-08-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance_after',
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='walletid',
            name='walletid',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
