# Generated by Django 3.2.14 on 2022-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
